import { ThemeProvider } from "@components/theme-provider";
import "./globals.scss";
import FileUploadForm from "@components/FileUploadForm";
import { ThemeToggle } from "@/components/theme-toggle";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <section className="flex justify-between w-full p-8">
            <FileUploadForm />
            <ThemeToggle />
          </section>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
